using System.Numerics;
using BeastmasterAssist.Combat;
using BeastmasterAssist.Data;
using BeastmasterAssist.Tracking;
using Dalamud.Bindings.ImGui;
using Dalamud.Interface.Windowing;
namespace BeastmasterAssist.Ui;
public sealed class OverlayWindow : Window
{
 private readonly Configuration config; private readonly CombatState state; private readonly RotationAdvisor rotation; private readonly ReactionAdvisor reactions; private readonly MitigationAdvisor mitigation; private readonly CaptureTracker capture; private readonly LevelingAdvisor leveling;
 private DateTime nextSnapshotAt=DateTime.MinValue,playerZeroSince=DateTime.MinValue,familiarZeroSince=DateTime.MinValue; private int displayedPlayerTp,displayedFamiliarTp; private string captureText=""; private List<Advice> rotationSnapshot=[],reactionSnapshot=[],mitigationSnapshot=[]; private List<LevelingAdvisor.Spot> levelingSnapshot=[];
 public OverlayWindow(Configuration config,CombatState state,RotationAdvisor rotation,ReactionAdvisor reactions,MitigationAdvisor mitigation,CaptureTracker capture,LevelingAdvisor leveling):base("Beastmaster Assist##BeastmasterAssistOverlay",ImGuiWindowFlags.NoCollapse){this.config=config;this.state=state;this.rotation=rotation;this.reactions=reactions;this.mitigation=mitigation;this.capture=capture;this.leveling=leveling;RespectCloseHotkey=false;Size=new Vector2(380,0);SizeCondition=ImGuiCond.FirstUseEver;}
 public override void PreDraw(){Flags=ImGuiWindowFlags.NoCollapse;if(config.LockOverlay)Flags|=ImGuiWindowFlags.NoMove|ImGuiWindowFlags.NoResize;ImGui.SetNextWindowBgAlpha(.90f);ImGui.PushStyleVar(ImGuiStyleVar.WindowRounding,10f);ImGui.PushStyleVar(ImGuiStyleVar.FrameRounding,6f);ImGui.PushStyleVar(ImGuiStyleVar.WindowPadding,new Vector2(14,12));ImGui.PushStyleVar(ImGuiStyleVar.ItemSpacing,new Vector2(6,6));}
 public override void PostDraw()=>ImGui.PopStyleVar(4);
 public override void Draw(){UiText.Sync(config);RefreshSnapshot();UpdateDisplayedTp();var scale=Math.Clamp(config.OverlayScale,.60f,1.80f);ImGui.SetWindowFontScale(scale);DrawHeader(scale);DrawGauges(scale);DrawSection(UiText.Rotation,new Vector4(1,.8f,.3f,1),()=>DrawAdviceList(rotationSnapshot,3));if(config.ShowReactions&&reactionSnapshot.Count>0)DrawSection(UiText.Reactions,new Vector4(1,.45f,.4f,1),()=>DrawAdviceList(reactionSnapshot,2));if(config.ShowMitigation&&mitigationSnapshot.Count>0)DrawSection(UiText.Mitigation,new Vector4(.4f,.75f,1,1),()=>DrawAdviceList(mitigationSnapshot,2));if(levelingSnapshot.Count>0)DrawSection(UiText.Leveling,new Vector4(.75f,.55f,1,1),DrawLevelingList);if(config.ShowCaptureHud&&!string.IsNullOrEmpty(captureText))DrawSection(UiText.Capture,new Vector4(.55f,1,.55f,1),()=>ImGui.TextWrapped(captureText));ImGui.SetWindowFontScale(1);}
 private void UpdateDisplayedTp(){var now=DateTime.UtcNow;displayedPlayerTp=StabilizeTp(state.PlayerTp,displayedPlayerTp,ref playerZeroSince,now);displayedFamiliarTp=StabilizeTp(state.FamiliarTp,displayedFamiliarTp,ref familiarZeroSince,now);}
 private static int StabilizeTp(int raw,int shown,ref DateTime zeroSince,DateTime now){raw=Math.Clamp(raw,0,250);if(raw>0){zeroSince=DateTime.MinValue;return raw;}if(shown==0)return 0;if(zeroSince==DateTime.MinValue)zeroSince=now;return now-zeroSince>=TimeSpan.FromMilliseconds(250)?0:shown;}
 private void DrawHeader(float scale){var accent=state.InCombat?new Vector4(1,.35f,.3f,1):new Vector4(.35f,.85f,.45f,1);var p=ImGui.GetCursorScreenPos();ImGui.GetWindowDrawList().AddCircleFilled(p+new Vector2(6*scale,8*scale),5*scale,ImGui.ColorConvertFloat4ToU32(accent));ImGui.Dummy(new Vector2(16*scale,0));ImGui.SameLine();ImGui.TextColored(new Vector4(1,.85f,.35f,1),"BEASTMASTER ASSIST");ImGui.SameLine();ImGui.TextDisabled(state.Player is not null?$"Lv{state.Level}":UiText.NoPlayer);if(ImGui.SmallButton("-"))SetScale(config.OverlayScale-.1f);ImGui.SameLine();if(ImGui.SmallButton($"{config.OverlayScale*100f:0}%"))SetScale(1);ImGui.SameLine();if(ImGui.SmallButton("+"))SetScale(config.OverlayScale+.1f);ImGui.SameLine();if(ImGui.SmallButton(UiText.HideOverlay))UiNavigator.ToggleOverlay?.Invoke();ImGui.Separator();}
 private void SetScale(float value){config.OverlayScale=Math.Clamp(value,.60f,1.80f);config.Save();}
 private void DrawGauges(float scale){var h=26*scale;ImGui.PushStyleColor(ImGuiCol.PlotHistogram,new Vector4(1,.72f,.2f,1));ImGui.ProgressBar(displayedPlayerTp/250f,new Vector2(-1,h),$"TP {displayedPlayerTp}/250");ImGui.PopStyleColor();ImGui.PushStyleColor(ImGuiCol.PlotHistogram,new Vector4(.35f,.70f,1,1));ImGui.ProgressBar(displayedFamiliarTp/250f,new Vector2(-1,h),$"{UiText.FamiliarLabel} {displayedFamiliarTp}/250");ImGui.PopStyleColor();ImGui.TextDisabled($"{state.ActiveKinship}   {BestiaryCatalog.BeastModeName(state.ActiveKinship)}");ImGui.Spacing();}
 private static void DrawSection(string t,Vector4 c,Action body){ImGui.Spacing();ImGui.TextColored(c,t.ToUpperInvariant());ImGui.PushStyleColor(ImGuiCol.Separator,c);ImGui.Separator();ImGui.PopStyleColor();ImGui.Indent(8);body();ImGui.Unindent(8);} private static void DrawAdviceList(List<Advice> a,int max){foreach(var x in a.Take(max)){ImGui.BulletText(x.Action);ImGui.SameLine();ImGui.TextDisabled(x.Reason);}}
 private void DrawLevelingList(){for(var i=0;i<levelingSnapshot.Count;i++){var s=levelingSnapshot[i];var tag=s.Captured?UiText.Captured:UiText.Missing;ImGui.TextColored(i==0?new Vector4(.85f,.70f,1,1):new Vector4(.9f,.9f,.9f,1),i==0?$"-> Lv{s.Level} {s.Name} ({tag})":$"• Lv{s.Level} {s.Name} ({tag})");ImGui.Indent(12);ImGui.TextWrapped(s.Location);ImGui.Unindent(12);}}
 private void RefreshSnapshot(){if(DateTime.UtcNow<nextSnapshotAt)return;nextSnapshotAt=DateTime.UtcNow.AddMilliseconds(750);captureText=capture.CapturePrompt;rotationSnapshot=rotation.Advise(state);reactionSnapshot=reactions.Advise(state);mitigationSnapshot=mitigation.Advise(state);levelingSnapshot=leveling.Suggest(state.Level,capture.Has);}
}
